---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: post-starwars
  labels:
    test: asdsxxxcxcxcss
spec:
  metrics:
  - name: starw-api-1
    count: '2'
    interval: 5s
    failureLimit: 1
    successCondition: result == '172'
    provider:
      web:
        url: https://swapi.py4e.com/api/people/1
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.height}"
---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pre-job
spec:
  metrics:
  - name: pass-always
    count: 2
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:3.8
                command: [sh, -c]
                args: [exit 0]
              restartPolicy: Never
          backoffLimit: 0