apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj-labs/argocd-monorepo-controller/refs/heads/main/manifests/install.yaml

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: argocd-monorepo-controller
  patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: rt-fork

patchesStrategicMerge:
- |
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: argocd-monorepo-controller-network-policy
  $patch: delete
- |
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: argocd-monorepo-repo-server-network-policy
  $patch: delete
- |
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: argocd-monorepo-repo-server-redis-network-policy.yaml
  $patch: delete