apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: gs-promotion-template
spec:
  applicationSourceSelector:
    matchExpressions:
      - key: in-product
        operator: Exists
  priority: 0
  versionSource:
    file: version.yaml
    jsonPath: $.appVersionRef
  promotion:
    Chart.yaml:
      jsonPaths:
        - $.appVersion
    version.yaml:  # Attributes from Chart.yaml to be promoted.
      jsonPaths:
        - $.appVersionRef  # Promotes the application version.
    values.yaml:
      jsonPaths:
        - $..image