apiVersion: apps/v1
kind: Deployment
metadata:
 name: the-deployment
 labels:
   deployment: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: demo
    spec:
      containers:
      - name: the-container
        image: gcr.io/cloud-marketplace/google/nginx1
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: mysqlDB
