apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupiter-deployment
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: xeonalex/guesbook:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
