kind: Kustomization
namePrefix: staging-
commonLabels:
  variant: staging
bases:
- ../../base
patchesStrategicMerge:
- config-map.yaml
images:
  - name: xeonalex/guesbook-unprivileged
    newTag: "v0.1.0"
