apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-test-4
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    canary:
      stableService: express-active
      canaryService: express-preview
      trafficRouting:
        nginx:
          stableIngress: express-stable-ingress
      # analysis:
      #   templates:
      #     - templateName: mixed-roll-tests
      #   startingStep: 1
      steps:
        - pause: {duration: 5000s}
        - analysis:
            templates:
            - templateName: mixed-roll-tests
        - setWeight: 50
        - pause: {duration: 4200s}
        
  selector:
    matchLabels:
      app: express-microservice
  template:
    metadata:
      labels:
        app: express-microservice
    spec:
      containers:
        - name: express-microservice
          image: xeonalex/guesbook:0.2
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
