namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-deployment-2.yaml
- guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: xeonalex/guesbook-unprivileged
  newTag: "7282b63"
- name: xeonalex/guesbook
  newTag: "v0.1.0"