---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: placeholder-analysis
  labels:
    showDiff: 'some-text10'
spec:
  metrics:
    - name: randfail
      count: 3
      interval: 10s
      failureLimit: 3
      provider:
        job:
          spec:
            template:
              spec:
                containers:
                  - name: sleep-fail
                    image: alpine:3.8
                    command: [sh, -c]
                    args: [FLIP=$(($(($RANDOM%10))%2)) && exit $FLIP]
                restartPolicy: Never
            backoffLimit: 0
