---
# Source: pdn-fc-v2-umbrella/templates/umbrella.cm.yaml
apiVersion: v1
data:
  NEW_RELIC_APP_NAME: pdn-fc-v2.preprod
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  NEW_RELIC_IGNORING_RULES: ^/appstatus$
  NEW_RELIC_LABELS: 'Environment: prod;DC: gnae1; Type: container'
  NEW_RELIC_LOG: stdout
  NEW_RELIC_LOG_LEVEL: warn
  NEW_RELIC_NO_CONFIG_FILE: "true"
kind: ConfigMap
metadata:
  labels:
    app: pdn-fc-v2
    cell: preprod
    track: primary
  name: pdn-fc-v2-preprod-primary
---
# Source: pdn-fc-v2-umbrella/templates/umbrella.svc.canary.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app: pdn-fc-v2
    application: pdn-fc-v2
    bu: tech
    cell: preprod
    product: sco
    team: pipeline
  name: pdn-fc-v2-preprod-canary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pdn-fc-v2
    cell: preprod
  type: ClusterIP
---
# Source: pdn-fc-v2-umbrella/templates/umbrella.svc.stable.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app: pdn-fc-v2
    application: pdn-fc-v2
    bu: tech
    cell: preprod
    product: sco
    team: pipeline
  name: pdn-fc-v2-preprod-stable
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pdn-fc-v2
    cell: preprod
  type: ClusterIP
---
# Source: pdn-fc-v2-umbrella/templates/umbrella.dr.yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    app: pdn-fc-v2
    cell: preprod
  name: pdn-fc-v2-preprod
spec:
  host: pdn-fc-v2-preprod
  subsets:
  - labels:
      track: primary
    name: primary-canary
  - labels:
      track: primary
    name: primary-stable
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
---
# Source: pdn-fc-v2-umbrella/templates/umbrella.rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    pcln.com/application: pdn-fc-v2
    pcln.com/argoApp: pdn-fc-v2.preprod.gnae1.non-pci.cfc.primary
    pcln.com/cfRuntime: cf-gitops-prod-guse4
    pcln.com/changeHtmlUrl: https://github.com/pcln/helm_configs/pull/495/files
    pcln.com/clusterFamily: non-pci
    pcln.com/env: preprod
    pcln.com/product: sco
    pcln.com/pullRequestHtmlUrl: https://github.com/pcln/helm_configs/pull/495
    pcln.com/pullRequestIssueUrl: https://api.github.com/repos/pcln/helm_configs/issues/495
    pcln.com/region: gnae1
    pcln.com/team: pipeline
    pcln.com/triggeringUserHtmlUrl: https://github.com/akorzy-pl
    pcln.com/version: master-0.0.37+helm_configs.111124
  labels:
    app: pdn-fc-v2
    application: pdn-fc-v2
    bu: tech
    cell: preprod
    multiClusterRolloutId: helm_configs.1111247aed200b8e759c36136559debcc4dfb6f2
    product: sco
    region: gnae1
    team: pipeline
    track: primary
  name: pdn-fc-v2-preprod-primary
spec:
  analysis:
    successfulRunHistoryLimit: 128
    unsuccessfulRunHistoryLimit: 128
  replicas: 1
  selector:
    matchLabels:
      app: pdn-fc-v2
      cell: preprod
      track: primary
  strategy:
    canary:
      canaryMetadata:
        labels:
          pcln.role: canary
      maxSurge: 25%
      maxUnavailable: 0%
      stableMetadata:
        labels:
          pcln.role: stable
      steps:
      - setWeight: 100
      - pause:
          duration: 1s
      - pause:
          duration: 2s
      - pause:
          duration: 2s
      - pause:
          duration: 2s
      - pause:
          duration: 1s
  template:
    metadata:
      labels:
        app: pdn-fc-v2
        application: pdn-fc-v2
        bu: tech
        cell: preprod
        product: sco
        team: pipeline
        track: primary
    spec:
      containers:
      - name: pdn-fc-v2
        image: xeonalex/guesbook:0.1
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: pdn-fc-v2
            cell: preprod
            track: primary
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            app: pdn-fc-v2
            cell: preprod
            track: primary
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      volumes:
      - emptyDir: {}
        name: temp-volume
---
# Source: pdn-fc-v2-umbrella/templates/umbrella.vs.mesh.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: pdn-fc-v2
    cell: preprod
  name: pdn-fc-v2-preprod-mesh-vs
spec:
  hosts:
  - pdn-fc-v2-preprod
  - pdn-fc-v2-preprod-canary
  - pdn-fc-v2-preprod-stable
  http:
  - name: primary
    route:
    - destination:
        host: pdn-fc-v2-preprod-canary
        subset: primary-canary
      weight: 0
    - destination:
        host: pdn-fc-v2-preprod-stable
        subset: primary-stable
      weight: 100
---
# Source: pdn-fc-v2-umbrella/templates/umbrella.vs.port.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pdn-fc-v2-preprod-http-vs
  labels:
    app: pdn-fc-v2
    cell: preprod
spec:
  hosts:
  - pdn-fc-v2-preprod
  - pdn-fc-v2-preprod-canary
  - pdn-fc-v2-preprod-stable
  http:
  # Use header based routing for non-primary tracks
  # When there is no header match, fall back to primary
  - name: primary
    route:
    - destination:
        host: pdn-fc-v2-preprod-canary
        port:
          number: 80
        subset: primary-canary
      weight: 0
    - destination:
        host: pdn-fc-v2-preprod-stable
        port:
          number: 80
        subset: primary-stable
      weight: 100
