---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: star-w-template-1
spec:
  metrics:
  - name: starw-api-1
    count: '2'
    interval: 5s
    failureLimit: 1
    successCondition: result == '172'
    provider:
      web:
        url: https://swapi.py4e.com/api/people/1
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.height}"
---

---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: star-w-template-15
spec:
  metrics:
  - name: starw-api-2
    count: 15
    interval: 5s
    successCondition: result == '172'
    # failureCondition: result != '2'
    failureLimit: 5
    provider:
      web:
        url: https://swapi.dev/api/people/1
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.height}"

---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: star-w-template-3-inconclusive
spec:
  metrics:
  - name: starw-api-2
    count: 2
    interval: 5s
    initialDelay: 5s
    inconclusiveLimit: 1
    consecutiveErrorLimit: 3
    failureCondition: result == '170'
    successCondition: result == '175'
    failureLimit: 2
    provider:
      web:
        url: https://swapi.dev/api/people/1
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.height}"

