apiVersion: v1
data:
  NEW_RELIC_APP_NAME: pdn-fc-v2.preprod
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: pdn-fc-v2
  name: pdn-fc-v2-preprod-primary