apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mars-rollout
  labels:
    testLabel: 'newvalue'
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    canary:
      steps:
        # - setWeight: 10
        # - pause: {duration: 30}
        - analysis:
            templates:
            - templateName: star-w-template-1
        - setWeight: 50
        - pause: {duration: 15}
  selector:
    matchLabels:
      app: express-microservice
  template:
    metadata:
      labels:
        app: express-microservice
    spec:
      containers:
        - name: express-microservice
          image: xeonalex/guesbook:0.1
          ports:
            - containerPort: 3070
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
