apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:3.8
        command: [sh, -c]
        args: [exit 1]
        resources: {}
      restartPolicy: Never
  backoffLimit: 4

