apiVersion: batch/v1
kind: Job
metadata:
  generateName: wait-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "60"]
      restartPolicy: Never
  backoffLimit: 0