apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: billing
  annotations:
    branch: "cr-2134"
spec:
  promotionTemplateRef: helmApps
  promotionTemplate:
    # Version Source Configuration:
    # Specifies the file and JSON path used to retrieve the application version for display in the dashboard.
    versionSource:
      file: Chart.yaml  # The file where the version is stored.
      jsonPath: $.appVersion  # JSON path to the version within the specified file.
    promotion:
      Chart.yaml:  # Attributes from Chart.yaml to be promoted.
        jsonPaths:
          - $.appVersion  # Promotes the application version.
          - $.version  # Promotes the version.
          - $.dependencies  # Promotes dependencies listed in the file.
      values.yaml:  # Attributes from values.yaml to be promoted.
        jsonPaths:
          - $.*.image  # Promotes the image specifications.
      requirements.yaml:  # Attributes from requirements.yaml to be promoted.
        jsonPaths:
          - "$.dependencies"  # Promotes dependencies.
  promotionFlows:
    - name: hotfix # matchers like in k8s - https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
      matchLabels:
        suitable-for: hotfix
      matchExpressions:
        - key: branch 
          operator: In # In / NotIn
          values:
            - hotfix
            - fix
        - key: commitMessage
          operator: In
          values:
            - hotfix
    - name: multiRegion
      matchExpressions:
        - key: commitMessage
          operator: In
          values:
            - promote