apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: demo
  annotations:
    version: 0.0.1
    description: 'Flow to show parallel deployment'
spec:
  triggerEnvironment: dev
  postTrigger: 'post-action'
  steps:
  - environment: qa
    dependsOn:
    - dev
    policy:
      preAction: 'pre-action'
      postAction: 'smoketests'
      action: commit
  - environment: staging
    dependsOn:
    - dev
    policy:
      preAction: 'pre-action'
      postAction: 'post-action'
      action: commit
  - environment: production
    dependsOn:
    - staging
    - qa
    policy:
      preAction: 'pre-action'
      postAction: 'post-action'
      action: commit
