apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express-roll
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
        # appss: exsspress
    spec:
      containers:
        - image: xeonalex/guesbook:0.2
          name: express
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  minReadySeconds: 30
  strategy:
    canary:
      steps:
        - setWeight: 20
        - analysis:
            templates:
            - templateName: star-w-template-3-inconclusive
        - pause: {duration: 50s}
        - pause: {duration: 40s}
