apiVersion: apps/v1
kind: Deployment
metadata:
    name: rand-{{ template "helm-guestbook.fullname" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: sleep-fail
        image: alpine:3.8
        command: [sh, -c]
        args: [FLIP=$(($(($RANDOM%10))%2)) && exit $FLIP]
      restartPolicy: Never