apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-2
spec:
  progressDeadlineSeconds: 60
  strategy:
    type: Recreate
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-2
  template:
    metadata:
      labels:
        app: guestbook-ui-2
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-2
        ports:
        - containerPort: 81
