apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-2 # sdsddsd
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: guestbook-ui-2
  template:
    metadata:
      labels:
        app: guestbook-ui-2
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-2
        ports:
        - containerPort: 81
