apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes-guesbook-promotion-configuration
  labels:
    in-product: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: products/promotion-configuration
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: hermes-prod-apps
  destination:
    name: in-cluster
    namespace: hermes-guestbook-configs
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      # selfHeal: true
    retry: {}
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
