kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: lightweight
spec:
  metrics:
  - name: starw-api-1
    count: 3
    interval: 5s
    failureLimit: 1
    successCondition: result == '172'
    provider:
      web:
        url: https://swapi.py4e.com/api/people/1
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.height}"